### ISSUE TITLE
Appropriate definition of alphabetical sort

### ISSUE THREAD

**Issue by SubhrajyotiSen** [muan/hello-world#116]
When we sort alphabetically, how do we handle lower and upper case alphabets?
I'm asking this because the PRs use sort in different ways.

**Comment by aaossa** [comment]
Maybe use the default output of `sort` ? :thinking: Seems like a good option

**Comment by callumacrae** [comment]
per my comment [here](https://github.com/muan/hello-world/pull/115/files#r134968199), there seems to be a difference in how things are sorted, though

**Comment by SubhrajyotiSen** [comment]
My doubt has been clarified. Thanks 😃
