### ISSUE TITLE
Hacktoberfest policy

### ISSUE THREAD

**Issue by SubhrajyotiSen** [muan/hello-world#226]
With Hacktoberfest starting, we will start getting a lot more pull requests, most of them being just placeholder PRs to qualify.
@muan What would be the suggested way to deal with the PRs this month?

**Comment by muan** [comment]
Thanks for dealing with these. I'm contemplating perhaps limiting interaction for the month, like many others have done? I don't think it is worth the effort.

Do you have a preference?

**Comment by SubhrajyotiSen** [comment]
I would be in favor of limiting interaction too.

**Comment by muan** [comment]
Thanks. It’s now limited to past contributors for this month.

Also thank you for your continued effort for this repository!
