### ISSUE TITLE
Fork and sync

### ISSUE THREAD

**Issue by linlinlinlin** [muan/hello-world#23]
想請教
-  Fork 出來的，要怎麼跟原本的來源同步？包含 tag (怎樣的步驟才是對的)
-  同步的時候，怎麼 merge 才是正確的步驟，或是遇到衝突的時候要怎麼處理，
  之前曾經練習過，但好像每次更新都會有一筆 merge 的 log
- 如果來源更新 tag (release) 的時候，Fork 出來的有辦法馬上知道嗎？ (還是只能透過UI上的Watch)

**Comment by muan** [comment]
1. 直接 pull upstream 的 branch 或 tag 來更新，並解決 conflicts。（但不同案例可能有各自適合的方法）
2. 這問題可能要詳細一點？每次 merge 不管有沒有 conflict 是都會有 merge commit 的。
3. 目前 GitHub 沒有 release notification，但可以訂閱特定 repository 的 releases feed，例如 https://github.com/muan/github-gmail/releases.atom 。
