### ISSUE TITLE
I can help!

### ISSUE THREAD

**Issue by alfredxing** [muan/hello-world#3]
I'd be happy to help review PR's and answer any questions!

Also: I don't think we have permissions to add the `i can help` label ourselves, so we might want to think of something else.

**Comment by muan** [comment]
Awesome! :raised_hands: I've added you. 

> Also: I don't think we have permissions to add the i can help label ourselves, so we might want to think of something else.

Ahhh good point. Perhaps just add to the title then, something like `[icanhelp] muan`?

**Comment by callumacrae** [comment]
This is awesome :clap: :confetti_ball: 

If this project gets popular and you need help reviewing PRs, I can help :smile:

**Comment by muan** [comment]
@callumacrae :wave: I've also added you to the repository! Thanks!

Re: how people volunteer, I've got an idea: we should probably keep a list of maintainers, and whoever wants to help just PR to that list, and I'll merge after I add the person. :+1:?

**Comment by callumacrae** [comment]
Woohoo! :smiley_cat:

Sounds good :)
